apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Backend deploy aumento de replicas a 4"
  name: deploy-back
  labels:
    app: backend
    env: des
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:      
       - name: back1
         image: python:3.6-alpine
         command: ['sh', '-c', ' echo back1 > index.html && python -m http.server 8082']
---
apiVersion: v1
kind: Service
metadata:
  name: service-back
  labels:
    app: backend
spec:
  type: ClusterIP      
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
