apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Frontend deploy v3"
  name: deploy-front
  labels:
    app: frontend
    env: des
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:      
       - name: front1
         image: swarthydj/ngxtest:v1
---
apiVersion: v1
kind: Service
metadata:
  name: service-fron
  labels:
    app: frontend
spec:
  type: NodePort      
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
